services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-fyp
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.0
    container_name: redis-fyp
    restart: unless-stopped
    ports:
      - "6379:6379"

  libre:
    image: libretranslate/libretranslate
    profiles:
      - translation
    container_name: libre-fyp
    restart: unless-stopped
    command: ["--load-only", "en,zh"]
    ports:
      - "5000:5000"
    mem_limit: 512m

  backend:
    image: pingan-mobile-app-backend
    build: ./backend
    container_name: fyp-backend
    restart: unless-stopped
    env_file:
      - ./infra/.env
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    environment:
      IP_ADDR: 0.0.0.0
      ENABLE_LIBRE_TRANSLATE: ${ENABLE_LIBRE_TRANSLATE:-false}

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      LIBRE_URL: ${LIBRE_URL:-http://libre:5000/translate}
    ports:
      - "8080:8080"
    networks:
      - default
      - db
    tty: true


  seed-admin:
    image: pingan-mobile-app-backend
    build: ./backend
    profiles:
      - tools
    restart: "no"
    env_file:
      - ./infra/.env
    environment:
      IP_ADDR: 0.0.0.0
      APP_TOOL: seed-admin
      APP_SEED_ADMIN_EMAIL: "${APP_SEED_ADMIN_EMAIL:-admin@gmail.com}"
      APP_SEED_ADMIN_PASSWORD: "${APP_SEED_ADMIN_PASSWORD:-12345678}"
      APP_SEED_ADMIN_FIRST_NAME: "${APP_SEED_ADMIN_FIRST_NAME:-John}"
      APP_SEED_ADMIN_LAST_NAME: "${APP_SEED_ADMIN_LAST_NAME:-Cena}"
      APP_SEED_ADMIN_RESET_PASSWORD: "${APP_SEED_ADMIN_RESET_PASSWORD:-false}"
      ENABLE_LIBRE_TRANSLATE: false
    networks:
      - db
networks:
  db:
    name: ${DB_NETWORK_NAME:-pingan-db-net}
    external: true