package com.fyp.backend.service.bible;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * One row of a translation, as generated by {@code backend/tools/ebible-to-json}.
 *
 * {@code verseEnd} differs from {@code verse} only on a bridged verse — the CUV
 * merges 70 pairs that the KJV numbers separately — and the generator omits the
 * field entirely everywhere else, hence the default in the constructor.
 */
public record BibleVerse(
        @JsonProperty("b") int book,
        @JsonProperty("c") int chapter,
        @JsonProperty("v") int verse,
        @JsonProperty("ve") Integer bridgedTo,
        @JsonProperty("t") String text) {

    public int verseEnd() {
        return bridgedTo == null ? verse : bridgedTo;
    }

    public boolean isBridged() {
        return bridgedTo != null && bridgedTo > verse;
    }
}
