import type { LocalizedText, SpiritualGiftQuestion } from "./spiritualGiftData";

const QUESTION_TEXTS: LocalizedText[] = [
  { zh: "我乐意传达从神直接给我的信息，这信息可以造就、劝勉和安慰别人。", en: "I am willing to share a message I believe God has given me directly when it can strengthen, encourage, and comfort others." },
  { zh: "我曾很乐意长期关心一些基督徒，分享他们的成功与失败。", en: "I have gladly cared for some Christians over a long period and shared in both their successes and failures." },
  { zh: "别人曾告诉我，他们觉得我能帮助他们学习圣经真理。", en: "Others have told me that I help them learn biblical truth." },
  { zh: "在日常生活中，我曾有效地应用圣经真理。", en: "I have applied biblical truth effectively in everyday life." },
  { zh: "别人曾告诉我，我有发掘经文要点和重要事实的能力。", en: "Others have told me that I can identify key points and important facts in Scripture." },
  { zh: "我曾用话语鼓励犹豫、困扰或灰心的人。", en: "I have used words to encourage people who were hesitant, troubled, or discouraged." },
  { zh: "教会中的人曾告诉我，我辨别真假的能力比大多数人敏锐。", en: "People in the church have told me that I recognize what is true or false sooner than most people do." },
  { zh: "我发现自己有理财能力，因此能为神的工作慷慨奉献。", en: "I find that I manage money well and can give generously to God's work." },
  { zh: "我曾帮助教会领袖处理琐碎工作，使他们能专心处理更重要的事。", en: "I have helped church leaders with routine tasks so they could concentrate on more important work." },
  { zh: "我愿意帮助身体或心灵上有困难的人，减轻他们的痛苦。", en: "I am willing to help people with physical or emotional difficulties in order to ease their suffering." },
  { zh: "我容易适应其他国家的人、风俗和文化，他们也愿意接纳我。", en: "I adapt easily to people, customs, and cultures from other countries, and they tend to accept me." },
  { zh: "我曾带领人信主。", en: "I have led people to faith in Christ." },
  { zh: "我乐意开放自己的家，接待旅途中有需要的人。", en: "I gladly open my home to travelers and others who need hospitality." },
  { zh: "在小组讨论或会议中，别人常询问我对方向或异象的看法。", en: "In group discussions or meetings, people often ask me for a sense of direction or vision." },
  { zh: "当我说话时，别人愿意聆听，也常认同我所说的。", en: "When I speak, people are willing to listen and often agree with what I say." },
  { zh: "当我身处缺乏组织的团契时，我会主动承担管理责任。", en: "When I am in an unorganized fellowship, I tend to take responsibility for organizing it." },
  { zh: "别人曾指出，因为我的祷告而发生了神迹。", en: "Others have pointed out that miracles occurred in response to my prayers." },
  { zh: "我曾奉主的名为疾病祷告，并立即看见果效。", en: "I have prayed for illness in the Lord's name and seen an immediate result." },
  { zh: "我曾说过方言。", en: "I have spoken in tongues." },
  { zh: "有时当人在公开聚会中说方言，我知道神要表达什么。", en: "At times when someone speaks in tongues in a public gathering, I know what God intends to communicate." },
  { zh: "我有能力过物质丰富的生活，却选择与贫穷的人一同生活。", en: "I could live with greater material comfort, but I choose to live alongside people who are poor." },
  { zh: "我是单身，并且享受单身生活。", en: "I am single and enjoy living as a single person." },
  { zh: "我每天至少祷告一小时。", en: "I pray for at least one hour each day." },
  { zh: "我曾对邪灵说话，而邪灵顺服了。", en: "I have spoken to evil spirits and they have obeyed." },
  { zh: "我很愿意接受教会交给我的特殊工作。", en: "I am very willing to take on specific tasks that the church asks me to do." },

  { zh: "借着神的启示，我会告诉别人即将或将来要发生的事。", en: "Through what I understand as God's revelation, I have told others about something that was going to happen." },
  { zh: "我乐意负责照顾一些基督徒，使他们的属灵生命保持健全。", en: "I gladly take responsibility for caring for some Christians so that they remain spiritually healthy." },
  { zh: "我觉得自己能清楚讲解新约中有关教会的真理。", en: "I believe I can explain New Testament truths about the church clearly and soundly." },
  { zh: "我能以直觉和洞见解答复杂的问题。", en: "I can use insight and intuition to find answers to complex problems." },
  { zh: "我能深入理解圣经真理，帮助弟兄姊妹更亲近主。", en: "I can gain insight into biblical truth in ways that help other believers draw closer to the Lord." },
  { zh: "我能有效地鼓励别人参与服事，特别是在有需要的时候。", en: "I can effectively motivate others to serve, especially when a need arises." },
  { zh: "我有时能清楚察觉神的灵正在某些弟兄姊妹身上工作。", en: "At times I can clearly perceive when God's Spirit is at work in another believer." },
  { zh: "从我的奉献记录来看，我每年奉献超过收入的百分之十。", en: "My giving records show that I contribute more than ten percent of my income each year." },
  { zh: "别人告诉我，因为我的帮助，他们能更有效地服事主。", en: "Others have told me that my help enabled them to serve the Lord more effectively." },
  { zh: "别人身体或物质上有需要时，我曾切实照顾他们。", en: "I have provided practical care when others had physical or material needs." },
  { zh: "我能学习并掌握外国语言，用来在另一种文化中服事主。", en: "I can learn and become proficient in another language for ministry in a different culture." },
  { zh: "我曾向未信者分享自己的信主经历，而他们对福音有良好回应。", en: "I have shared my testimony with unbelievers and they responded positively to the gospel." },
  { zh: "我乐意负责筹办教会爱宴和其他社交活动。", en: "I gladly take responsibility for church meals and other social gatherings." },
  { zh: "我相信神能成就一般人认为不可能的事，并且确实见过祂成就。", en: "I believe God can do what most people consider impossible, and I have seen Him do so." },
  { zh: "其他基督徒愿意跟随我的带领，因为他们信任我。", en: "Other Christians are willing to follow my leadership because they trust me." },
  { zh: "我能组织人力、知识、财力和时间，使服事更有效。", en: "I can organize people, knowledge, finances, and time so that ministry becomes more effective." },
  { zh: "神曾借着我行出奇妙的神迹。", en: "God has worked remarkable miracles through me." },
  { zh: "我乐意为病人祷告，因为我相信许多人会得到医治。", en: "I gladly pray for sick people because I believe many will be healed." },
  { zh: "我曾用自己没有学过的语言向神的儿女传达信息。", en: "I have communicated a message to God's people in a language I never learned." },
  { zh: "我曾翻方言，使教会肢体得到造就、劝勉和安慰。", en: "I have interpreted tongues in a way that strengthened, encouraged, and comforted the church." },
  { zh: "简朴生活对我来说是一项有吸引力的挑战。", en: "Living simply is an appealing challenge to me." },
  { zh: "别人发现我能泰然地过单身生活，并不向往婚姻。", en: "Others observe that I am content in single life and do not long for marriage." },
  { zh: "当我得知一项代祷需要时，通常会为它持续祷告好几天。", en: "When I learn of a prayer need, I usually pray for it over several days." },
  { zh: "我曾亲耳听见邪灵大声说话。", en: "I have personally heard an evil spirit speak aloud." },
  { zh: "即使没有特别的专长，我也常在教会中完成需要有人做的事。", en: "Even without a special skill for the task, I regularly do whatever needs to be done in the church." },

  { zh: "别人告诉我，我能在适当且有需要的时候向他们传达从神而来的信息。", en: "Others have told me that I delivered a message from God at the right and needed time." },
  { zh: "我不怕给基督徒属灵上的引导和方向。", en: "I am not afraid to give Christians spiritual guidance and direction." },
  { zh: "我愿意花许多时间学习圣经真理，以便有效地教导别人。", en: "I am willing to spend considerable time studying biblical truth so that I can teach others effectively." },
  { zh: "当别人遇到问题时，我常能从圣经中为他们找到合适的答案。", en: "When others face problems, I can often find an appropriate answer for them in Scripture." },
  { zh: "通过学习和经验，我能辨别有助于神国发展的策略和方法。", en: "Through study and experience, I can identify strategies and methods that help God's kingdom advance." },
  { zh: "别人在痛苦中寻求我的帮助，许多人告诉我他们得到帮助或医治。", en: "People seek my help in times of distress, and many tell me that they have been helped or healed." },
  { zh: "我能相当准确地察觉一个人是否受到邪灵困扰。", en: "I can recognize with considerable accuracy when a person is troubled by an evil spirit." },
  { zh: "当神的工作有需要而我感动奉献时，我通常能找到可奉献的钱。", en: "When God's work has a need and I feel led to give, I can usually find money to contribute." },
  { zh: "我很乐意承担普通的日常工作，使别人的服事更有效。", en: "I gladly do ordinary daily work so that another person's ministry can be more effective." },
  { zh: "我乐意探访医院或养老院中的人，而且这项服事常有果效。", en: "I gladly visit people in hospitals or care homes, and this ministry is often fruitful." },
  { zh: "不同种族和文化的人吸引我，我也容易与他们建立良好关系。", en: "I am drawn to people of different races and cultures and build good relationships with them." },
  { zh: "未信者与我相处时感到自在，并告诉我，我对他们的信仰思考有所帮助。", en: "Unbelievers feel comfortable with me and say that I have helped them think about faith." },
  { zh: "别人来到我家时通常感到轻松自在。", en: "People generally feel relaxed and at home when they visit my home." },
  { zh: "别人告诉我，我有信心成就一般人认为不可能的事。", en: "Others have told me that I have faith to accomplish what most people consider impossible." },
  { zh: "当我设立目标时，别人通常很容易接受。", en: "When I set a goal, other people usually accept it readily." },
  { zh: "我一直能够为群体目标的完成制定有效计划。", en: "I have consistently been able to make effective plans for achieving group goals." },
  { zh: "神常使用我完成一些看似不可能的奇妙工作。", en: "God often uses me to accomplish remarkable work that appears impossible." },
  { zh: "别人告诉我，神借着我的辅导医治了他们心灵或情绪上的创伤。", en: "Others have told me that God healed emotional or inner wounds through my counsel." },
  { zh: "我能用自己从未学过的语言与神交流。", en: "I can communicate with God in a language I have never learned." },
  { zh: "我曾祷告求神赐给我翻方言的能力。", en: "I have prayed for God to give me the ability to interpret tongues." },
  { zh: "我并不贫穷，却能够认同并亲近贫穷的人。", en: "I am not poor, yet I can identify closely with people who are poor." },
  { zh: "因为单身让我有更多时间服事神，我对此感到喜乐。", en: "I am glad that being single gives me more time to serve God effectively." },
  { zh: "我喜欢代祷，也经常这样做。", en: "I enjoy intercessory prayer and practice it regularly." },
  { zh: "当有人似乎受到邪灵困扰时，别人会请我前去帮助。", en: "People ask me to help when someone appears to be troubled by an evil spirit." },
  { zh: "别人会提到我喜欢做普通的日常工作，而且做得不错。", en: "Others notice that I enjoy ordinary daily tasks and do them well." },

  { zh: "有时我强烈感到神要我针对某件特别的事向某人说话。", en: "At times I strongly sense that God wants me to speak to someone about a particular matter." },
  { zh: "我曾引用合适的经文帮助有需要的人，并与他们一同祷告。", en: "I have used appropriate Scripture to help someone in need and prayed with that person." },
  { zh: "我能有效地向别人讲解圣经真理，并看见他们的知识、态度、价值观或观念因此更符合圣经。", en: "I can communicate biblical truth effectively and see people's knowledge, attitudes, values, or ideas change to align more closely with Scripture." },
  { zh: "有人曾说，我能理解并应用圣经真理来帮助主内弟兄姊妹。", en: "People have said that I understand and apply biblical truth in ways that help other believers." },
  { zh: "我常研读许多书籍，为要更深入学习圣经真理。", en: "I regularly study many books in order to understand biblical truth more deeply." },
  { zh: "我乐意有效地帮助迷惘、内疚或受不良嗜好捆绑的人。", en: "I gladly help people who are confused, burdened by guilt, or trapped in harmful habits." },
  { zh: "我能清楚辨别一种教导是出于神、出于魔鬼，还是出于人的意思。", en: "I can clearly discern whether a teaching comes from God, from evil, or merely from human ideas." },
  { zh: "我确信神会供应一切所需，因此经常作出牺牲性的奉献。", en: "I am confident that God will provide what I need, so I often give sacrificially." },
  { zh: "当我在幕后工作而别人因此得到帮助时，我感到很喜乐。", en: "I feel great joy when I work behind the scenes and others are helped as a result." },
  { zh: "别人愿意请我去帮助处于困难中的人。", en: "People are willing to ask me to help someone who is going through difficulty." },
  { zh: "如果能让更多人听见福音，我愿意离开目前舒适的环境。", en: "I am willing to leave my present comfort if doing so will help more people hear the gospel." },
  { zh: "当我看见其他基督徒不像我一样经常向未信者传福音时，我会感到挫折。", en: "I become frustrated when I see other Christians sharing the gospel with unbelievers less often than I do." },
  { zh: "别人告诉我，我很善于接待，也愿意招待人。", en: "Others tell me that I am hospitable and willing to welcome people." },
  { zh: "有时当别人还不能确定时，我已经知道神对未来工作的特别旨意。", en: "Sometimes I know God's particular purpose for future work before others are certain of it." },
  { zh: "当我参加一个团契时，别人常会退后一步并期待我来带领。", en: "When I join a fellowship, others often step back and look to me for leadership." },
  { zh: "我能清楚指导别人完成工作，而不需要反复说服他们。", en: "I can direct people in completing a task without repeatedly persuading them." },
  { zh: "别人告诉我，神曾以超自然的方式使用我改变他们的生命或处境。", en: "Others have told me that God used me in a supernatural way to change their life or circumstances." },
  { zh: "我曾为别人的身体疾病祷告，而他们得到医治。", en: "I have prayed for another person's physical illness and seen that person healed." },
  { zh: "当我在聚会中用方言传递信息时，我期待有人能够翻出来。", en: "When I give a message in tongues during a gathering, I expect someone to interpret it." },
  { zh: "我翻方言的方式似乎能祝福别人。", en: "My interpretation of tongues appears to bring blessing to others." },
  { zh: "别人告诉我，我常作出牺牲性的奉献，以便更有效地服事主。", en: "Others have told me that I often give sacrificially in order to serve the Lord more effectively." },
  { zh: "我是单身，并且在节制性欲方面没有太大困难。", en: "I am single and do not have great difficulty exercising sexual self-control." },
  { zh: "别人告诉我，我为他们所作的祷告得到了明确的回应。", en: "Others have told me that prayers I offered for them received clear answers." },
  { zh: "当我祷告时，别人曾立刻从邪灵的压制中得到释放。", en: "When I prayed, people were immediately released from demonic oppression." },
  { zh: "比起坐着讨论、阅读或听讲，我更喜欢亲自投入工作。", en: "I prefer getting personally involved in the work rather than sitting and discussing, reading, or listening." },

  { zh: "有时我确切知道神要在某项事工中做什么，以及何时去做。", en: "At times I know clearly what God intends to do in a ministry and when it should be done." },
  { zh: "别人告诉我，我曾帮助他们回到神的家中。", en: "Others have told me that I helped them return to fellowship in God's family." },
  { zh: "研读圣经并与人分享心得，对我来说是一大享受。", en: "Studying Scripture and sharing what I learn with others is a great joy to me." },
  { zh: "面对重大决定时，我曾感到神不同寻常的同在，并有坚定的信心。", en: "When facing major decisions, I have sensed God's presence in an unusual way and experienced strong confidence." },
  { zh: "当我阅读或观察事情时，我有能力从第一手资料中发现神的真理。", en: "When I read or observe events, I can discover truths from primary information that others may overlook." },
  { zh: "我会劝勉在苦难中的基督徒从圣经中寻找答案。", en: "I encourage Christians who are suffering to seek answers in Scripture." },
  { zh: "我能辨别一个人是否真正地在说方言。", en: "I can discern whether a person is genuinely speaking in tongues." },
  { zh: "为了神的工作，我曾把自己的物质生活水平至少降低一个层次。", en: "For the sake of God's work, I have lowered my material standard of living by at least one level." },
  { zh: "服事主时，我不在乎谁得到称赞或荣誉。", en: "When serving the Lord, I do not care who receives the credit or recognition." },
  { zh: "我喜欢用喜乐而有活力的话鼓励孤独、行动不便或在监狱中的人。", en: "I enjoy bringing cheerful, life-giving words to people who are lonely, homebound, or in prison." },
  { zh: "与大多数人相比，我更强烈地渴望看见其他国家和文化的人归主。", en: "Compared with most people, I have a stronger desire to see people of other nations and cultures come to Christ." },
  { zh: "未信主的人吸引我，我愿意带领他们归主。", en: "I am drawn to unbelievers and want to lead them to Christ." },
  { zh: "我常愿意开放自己的家给主的工人使用。", en: "I am often willing to make my home available to the Lord's workers." },
  { zh: "别人告诉我，我是一个很有异象的人，我也认同这一点。", en: "Others tell me that I am a person of strong vision, and I agree." },
  { zh: "当我担任领导者时，大多数事情都能顺利进行。", en: "When I serve as a leader, most things proceed smoothly." },
  { zh: "我享受为一项事工的成功承担责任。", en: "I enjoy taking responsibility for the successful completion of a ministry." },
  { zh: "我曾奉主的名叫失明的人看见。", en: "I have prayed in the Lord's name and seen a blind person receive sight." },
  { zh: "当我为病人祷告时，病人或我自己有时会感到热力或如触电般的感觉。", en: "When I pray for a sick person, that person or I sometimes feel warmth or a sensation like an electric current." },
  { zh: "我说方言时，相信主的肢体因此得到造就。", en: "When I speak in tongues, I believe members of the Body of Christ are strengthened." },
  { zh: "当我翻方言时，感觉信息像是直接从神而来。", en: "When I interpret tongues, the message seems to come directly from God." },
  { zh: "贫穷的人接纳我，因为我选择与他们一同过简朴清贫的生活。", en: "People who are poor accept me because I choose to share a simple and materially poor way of life with them." },
  { zh: "我能认同保罗希望其他人也像他一样保持独身。", en: "I can identify with Paul's desire that others might remain single as he did." },
  { zh: "当我祷告时，神常向我说话，而我知道祂的声音。", en: "When I pray, God often speaks to me, and I recognize His voice." },
  { zh: "我曾奉主耶稣基督的名赶鬼。", en: "I have cast out a demon in the name of the Lord Jesus Christ." },
  { zh: "当别人请我做看似低微或不重要的工作时，我乐意接受。", en: "When others ask me to do work that seems lowly or unimportant, I accept it gladly." },
];

if (QUESTION_TEXTS.length !== 125) {
  throw new Error(`Spiritual gift questionnaire must contain 125 questions, found ${QUESTION_TEXTS.length}`);
}

export const SPIRITUAL_GIFT_QUESTIONS: SpiritualGiftQuestion[] = QUESTION_TEXTS.map(
  (text, index) => ({ id: index + 1, text })
);
