#spring.application.name=chat
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/pingan_mobile_app
#spring.datasource.username=pingan_mobile_app_user
#spring.datasource.password=PinganMobileApp@2026
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#
#env.data.ip_addr=192.168.50.248

# Import external env.properties file
spring.config.import=optional:file:env.properties

# Use variables from env.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.address=${IP_ADDR}

spring.data.redis.host=redis-fyp
spring.redis.port=6379

# Email for password reset
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pinganservice572@gmail.com
spring.mail.password=ltwt dhsy jllc qulz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# === RABBITMQ CONFIG ===
spring.rabbitmq.host=rabbitmq-fyp
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest